@{
Page.Layout := 'Master.Layout';
Page.Title := 'Change Password';
}

<h2>Change Password</h2>
<p>
    Use the form below to change your password.
</p>

<script src="/Content/Js/jquery.validate.min.js" type="text/javascript"></script>
<script src="/Content/Js/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>

<form method="post">
    @Html.ValidationSummary('Password change was unsuccessful. Please correct the errors and try again.')
    <div>
        <fieldset>
            <legend>Account Information</legend>

            <div class="editor-label">
                @Html.HtmlLabel('Old Password')
            </div>
            <div class="editor-field">
                @Html.Password('OldPassword',Model.OldPassword)
                @Html.ValidationMessage('OldPassword','')
            </div>

            <div class="editor-label">
                @Html.HtmlLabel('New Password')
            </div>
            <div class="editor-field">
                @Html.Password('NewPassword',Model.NewPassword)
                @Html.ValidationMessage('NewPassword','')
            </div>

            <div class="editor-label">
                @Html.HtmlLabel('Confirm Password')
            </div>
            <div class="editor-field">
                @Html.Password('Confirm Password',Model.ConfirmPassword)
                @Html.ValidationMessage('ConfirmPassword','')
            </div>
            <p>
                <input type="submit" value="Change Password" />
            </p>
        </fieldset>
    </div>
</form>
