@{
Page.Title := 'Log On';
Page.Layout := 'Master.Layout';
}

<h2>Log On</h2>
<p>
    Please enter your user name and password. @Html.ActionLink('Register', 'Register','Account') if you don't have an account.
</p>

<script src="/Content/Js/jquery.validate.min.js" type="text/javascript"></script>
<script src="/Content/Js/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>

@Html.ValidationSummary('Login was unsuccessful. Please correct the errors and try again.')

@Html.FlashMessage()

<form method="post">
    <div>
        <fieldset>
            <legend>Account Information</legend>

            <div class="editor-label">
                @Html.HtmlLabel('UserName')
            </div>
            <div class="editor-field">
                @Html.TextBox('UserName',Model.UserName)
                @Html.ValidationMessage('UserName','')
            </div>

            <div class="editor-label">
                @Html.HtmlLabel('Password')
            </div>
            <div class="editor-field">
                @Html.Password('Password',Model.Password)
                @Html.ValidationMessage('Password','')
            </div>

            <div class="editor-label">
                @Html.HtmlLabel('RememberMe')
            </div>

            <p>
                <input type="submit" value="Log On" />
            </p>
        </fieldset>
    </div>
</form>
