

unit BOClasses;

interface
// This file was automatically generated by the mORMot T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ApplicationServices`
//     Provider:               `System.Data.SQLite`
//     Connection String:      `Data Source=App_Data\..\DataFiles\BlogDB.s3db;Version=3;`
//     Schema:                 ``
//     Include Views:          `True`
//     Factory Name:          `SQLiteFactory`

uses Classes,MvcDBCommon;

type
   
  [TMvcDBTableName('Post','')]
  TPost = class
  private
    FPostId: Integer;
    FTitle: String;
    FBody: String;
    FCreatedDate: TDateTime;
    FUpdatedDate: TDateTime;
  published
   [TMvcDBPrimaryKeyColumn]
    [TMvcDBAutoIncrementColumn]
    property PostId: Integer read FPostId write FPostId;
    property Title: String read FTitle write FTitle;
    property Body: String read FBody write FBody;
    property CreatedDate: TDateTime read FCreatedDate write FCreatedDate;
    property UpdatedDate: TDateTime read FUpdatedDate write FUpdatedDate;
  public
    constructor Create;overload;
    constructor CreateNew(APostId:Integer;ATitle:String;ABody:String;ACreatedDate:TDateTime;AUpdatedDate:TDateTime);overload;
  end;
   
  [TMvcDBTableName('Comment','')]
  TComment = class
  private
    FCommentId: Integer;
    FBody: String;
    FName: String;
    FEmail: String;
  published
   [TMvcDBPrimaryKeyColumn]
    [TMvcDBAutoIncrementColumn]
    property CommentId: Integer read FCommentId write FCommentId;
    property Body: String read FBody write FBody;
    property Name: String read FName write FName;
    property Email: String read FEmail write FEmail;
  public
    constructor Create;overload;
    constructor CreateNew(ACommentId:Integer;ABody:String;AName:String;AEmail:String);overload;
  end;
   
  [TMvcDBTableName('User','')]
  TUser = class
  private
    FUserId: Integer;
    FName: String;
    FPassword: String;
  published
   [TMvcDBPrimaryKeyColumn]
    [TMvcDBAutoIncrementColumn]
    property UserId: Integer read FUserId write FUserId;
    property Name: String read FName write FName;
    property Password: String read FPassword write FPassword;
  public
    constructor Create;overload;
    constructor CreateNew(AUserId:Integer;AName:String;APassword:String);overload;
  end;

implementation

   
constructor TPost.Create;
begin
  inherited Create;
end;

constructor TPost.CreateNew(APostId:Integer;ATitle:String;ABody:String;ACreatedDate:TDateTime;AUpdatedDate:TDateTime);
begin
  inherited Create;
  PostId:=APostId;
  Title:=ATitle;
  Body:=ABody;
  CreatedDate:=ACreatedDate;
  UpdatedDate:=AUpdatedDate;
end;

   
constructor TComment.Create;
begin
  inherited Create;
end;

constructor TComment.CreateNew(ACommentId:Integer;ABody:String;AName:String;AEmail:String);
begin
  inherited Create;
  CommentId:=ACommentId;
  Body:=ABody;
  Name:=AName;
  Email:=AEmail;
end;

   
constructor TUser.Create;
begin
  inherited Create;
end;

constructor TUser.CreateNew(AUserId:Integer;AName:String;APassword:String);
begin
  inherited Create;
  UserId:=AUserId;
  Name:=AName;
  Password:=APassword;
end;


end.